# Generated by Django 5.2.4 on 2025-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_state_profile_location_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
